sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: XY+XKQiLo1E4dOyR0nchFfTmzHtVF7n9ZYqlmfETjJ7GHF3MdAyusRRupKVYMdj95wvlkyyBH7nOS5lasEyU1+LdyRYcpTveqjFKbivP25LkbNf7blbuNArPLvmXPgBaB0GRChUL3iijr4Fa1D8aq0Em9VgJK8AID4zc4IU1VjLrdFo3Pr49jFoDtIS5JGojNwShS77G4pNdjEjYCvkFioXOY0l9mOACxhxbaw5SPxu7wbIiQ3OqOxEAjxCM6NNt+TLT8AZRmM93vlErE0bcpec0I7LlSaV1JUqiyRaGMMoLSCnffvQSvSQx78cR7vAOaWSRXc/moOUtAisjG1NIgiTUnOIpUIzUXcjpTs+WSWIrPsioxSMnCYwxMUzrW2ySjrxFFxAxpzk5mBrP1s3aH4E+SEhtdZTLzCWilX2Y4douuebteus7uTmcOinAL/yh1wQ7zfGBAR210E0XSxfQEjSQk2V5pfenjG+68oAN1QyrbK/z89cZGay0TSZef6ovB2+fzEK6slaVdY7FZMoXlMnmbcURNbfruwoW9x0wgUAaYEnx27bAUZ0iWtM8E5P27aanYvNbN1Oei8YypKtbkMJ/nNromSoNDuFkBUG2ty3/Ekk2H2iLM8qdEbmpLhE0U6RRmUb1aVVRmwFv6awpYnS3CaQl7gtqmA1ObsLQoq8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Memoirs-of-the-Court-of-Marie-Antoinette-Queen-of-France-Volume-2--13-Being-the-Historic-Memoi__3885
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy